export enum SPEACIAL_COMMAND_ENUNM {
    NEW_USER = "<NEW_USER>",
    EXIT_USER = "<EXIT_USER>",
    CREATE_GROUP = "<CREATE_ROOM>",
    DELETE_GROUP = "<DELETE_GROUP>",
    RENAME_GROUP = "<RENAME_GROUP>"
}